# [Choice] Ubuntu version: focal (20.04), bionic (18.04), xenial (16.04)
ARG VARIANT="9.13-slim"
FROM debian:${VARIANT}

# USER
ARG USERNAME=cb500
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Install needed packages
RUN apt-get update \
    && apt-get install -y sudo \
    && apt-get install -y --no-install-recommends gcc make git gdb

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************

# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME